### ISSUE TITLE
Bug: Dockerfile cannot build due to shapely dependency error

### ISSUE THREAD

**Issue by lwbayes** [eliiza/challenge-urban-forest#1]
Hi,

As per instruction, I cloned the repo and ran ``

I encountered the following error:
```bash
Step 3/8 : RUN pip install Shapely==1.6.4.post2
 ---> Running in ac52faf24733
WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Shapely==1.6.4.post2
  Downloading Shapely-1.6.4.post2.tar.gz (225 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z4r0nors/Shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z4r0nors/Shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gw63ko3o
         cwd: /tmp/pip-install-z4r0nors/Shapely/
    Complete output (11 lines):
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z4r0nors/Shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-z4r0nors/Shapely/shapely/_buildcfg.py", line 166, in <module>
        lgeos = load_dll('geos_c',
      File "/tmp/pip-install-z4r0nors/Shapely/shapely/_buildcfg.py", line 159, in load_dll
        raise OSError(
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/bash -o pipefail -c pip install Shapely==1.6.4.post2' returned a non-zero code: 1
```

Seems like the docker file does not work anymore due to changes in the upstream notebook image. 

Found solution here: https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants

PR to fix coming

**Comment by talestonini** [comment]
Fix merged 👍 
Thank you, Letian.
Regards, Tales
